### ISSUE TITLE
Features: adjust menu size to fit high resolution screens

### ISSUE THREAD

**Issue by dyphire** [tsl0922/mpv-menu-plugin#1]
Optimize menu display on high-definition screens, currently showing too small on 4k screens.

**Comment by butterw** [comment]
Some text size customization options would be nice to have. 
Different settings could be used for fullscreen (plenty of room to display a contextual menu) and in windowed mode (ex: on a 360p video). A menu that ends up being bigger than the video isn't good.

**Comment by dyphire** [comment]
> Some text size customization options would be nice to have.
> Different settings could be used for fullscreen (plenty of room to display a contextual menu) and in windowed mode (ex: on a 360p video). A menu that ends up being bigger than the video isn't good.

The right-click menu should not have any custom options other than custom menu items, it is not a UI.
When the right-click menu is limited to the window, it loses more usability, especially when the window is too small, it will be almost unusable. The menu behavior you mentioned does not exist in most players, and the right-click menu behavior in uosc scripts is only due to the limitations of MPV's OSD rendering.

**Comment by tsl0922** [comment]
- https://learn.microsoft.com/en-us/windows/win32/hidpi/high-dpi-desktop-application-development-on-windows
- https://learn.microsoft.com/en-us/windows/win32/api/winuser/nf-winuser-enablenonclientdpiscaling

> Note  Applications running at a [DPI_AWARENESS_CONTEXT](https://learn.microsoft.com/en-us/windows/desktop/hidpi/dpi-awareness-context) of DPI_AWARENESS_CONTEXT_PER_MONITOR_AWARE_V2 automatically scale their non-client areas by default. They do not need to call this function.

It seems mpv already have `PerMonitorV2`: https://github.com/mpv-player/mpv/blob/master/osdep/mpv.exe.manifest

**Comment by dyphire** [comment]
> It seems mpv already have `PerMonitorV2`: https://github.com/mpv-player/mpv/blob/master/osdep/mpv.exe.manifest

Yes, the mpv itself supports HIDPI. But the menu plugin doesn't support it yet. So the menus it renders on 2k and 4k screens do not have regular sizes.

**Comment by tsl0922** [comment]
I mean `EnableNonClientDpiScaling` should make Context Menu support HIDPI, but it seems not working on mpv.

Can not find a solution that don't require draw the menu myself yet.

**Comment by butterw** [comment]
The windows hidpi feature on is working for me. 
![mpv-plugin_150](https://github.com/tsl0922/mpv-plugin/assets/408915/89219735-32c9-409c-84e2-2b4c5e852289)
![mpv-plugin_100](https://github.com/tsl0922/mpv-plugin/assets/408915/ad7c8646-967d-43e4-92e6-af56aaf1d7fc)

menu.dll: 13 ‎December ‎2023, ‏‎08:31:28
I'm on Win10 22H2 with a 1440p monitor and I typically use 125% scaling.

**Comment by tsl0922** [comment]
I'm on Win10 22H2, 4K monitor. It seems to be working too.

Althrough the padding of menu item and font size is small than other applications.

**Comment by butterw** [comment]
I've checked and there is no difference with the Windows start bar contex menu Size. Firefox and Chrome context menu text size are also the same.

I find the horizontal (icon space) padding a bit too much.

**Comment by tsl0922** [comment]
Well, it's seems there's no way to change the menu font and item padding, unless [Creating Owner-Drawn Menu Items](https://learn.microsoft.com/en-us/windows/win32/menurc/using-menus#creating-owner-drawn-menu-items).

**Comment by dyphire** [comment]
> I'm on Win10 22H2, 4K monitor. It seems to be working too.
> 
> Althrough the padding of menu item and font size is small than other applications.

Yes, after further testing, I can confirm that HIDPI is effective.
The real problem here is that the size of the menu in full screen on a 4k screen is too small. I will correct the problem description. The following is a comparison of menu rendering between cplugins and mpv.net.
![image](https://github.com/tsl0922/mpv-plugin/assets/61936050/dee14bfa-9d48-4d90-87eb-c66fa30a036d)
![image](https://github.com/tsl0922/mpv-plugin/assets/61936050/bc1259b9-7432-4408-a923-8f49aecdb910)

**Comment by butterw** [comment]
In Win10, it's possible to tweak Menu Font size via windows registry (+ sign out). The setting affects all apps but the change was beneficial for me.
I changed the value from Segoe UI 9 to 10 and this solves the slightly too small menu text problem.

You can use the Winaero Tweaker app for this:
https://winaero.com/how-to-change-menu-row-height-in-windows-10-windows-8-1-and-windows-8/

**Comment by Youxikong** [comment]
This way is broken and too dirty.

**Comment by butterw** [comment]
If you think the displayed text is too small, you can also change the windows advanced hidpi setting.
