### ISSUE TITLE
Shorten the length of long string item names

### ISSUE THREAD

**Issue by hooke007** [tsl0922/mpv-menu-plugin#10]
Prepare for displaying track items.
![Snipaste_2023-12-16_00-42-00](https://github.com/tsl0922/mpv-plugin/assets/41094733/5b491644-62d8-4010-bd05-56d62970db9f)

**Comment by tsl0922** [comment]
I'll do it for dynamic items like tracks, but not the items from `input.conf`.

**Comment by tsl0922** [comment]
https://github.com/tsl0922/mpv-menu-plugin?tab=readme-ov-file#script-optsdyn_menuconf
