### ISSUE TITLE
Merge and display different key bindings for the same menu item

### ISSUE THREAD

**Issue by dyphire** [tsl0922/mpv-menu-plugin#18]
At present, when assigning different key bindings to the same menu item, the menu will display two menu items. The correct approach should be to merge the different key bindings and display them like mpv.net.

Additional implementation of #10 is required to optimize the display.

**Comment by tsl0922** [comment]
I think the correct approach should be removing the duplicate menu item definition.

As per https://github.com/mpv-player/mpv/issues/5500#issuecomment-1859881025, I'm not going to add such complex and non-essential logic/feature to this C plugin.

**Comment by tsl0922** [comment]
The v2 version of this plugin will split such logic to a lua script.

**Comment by dyphire** [comment]
> The v2 version of this plugin will split such logic to a lua script.

Sounds good, it's best to add a message handler that allows custom menu content to be rendered through third-party scripts. For example, extending the implementation of the nearest menu and playlist menu.
