### ISSUE TITLE
quality-menu youtube

### ISSUE THREAD

**Issue by candrapersada** [tsl0922/mpv-menu-plugin#25]
how to change the streamed video and audio quality (ytdl-format) in mpv-menu-plugin?

**Comment by tsl0922** [comment]
What you need is `--script-opts=ytdl_hook-all_formats=yes`, but it may not always work (https://github.com/mpv-player/mpv/issues/10394). If it works, you will be able to choose video and audio track under the Tracks menu.

It it doesn't work for you, try script like: https://github.com/christoph-heinrich/mpv-quality-menu, it's pretty easy to add a menu item to trigger the script.

**Comment by tsl0922** [comment]
For example, it works for [bilibili](https://www.bilibili.com) video:

<img width="463" alt="image" src="https://github.com/tsl0922/mpv-menu-plugin/assets/1680515/7f5cc73d-0b9f-431d-8fd5-4cad33f34c33">

**Comment by ywq0056** [comment]
Why is the menu interface you opened black, while mine is a white menu? Can you tell me how you set the black menu? I haven't found a way yet

**Comment by tsl0922** [comment]
You need to change the color scheme to dark in Windows Settings, no way to configure it in mpv yet.

**Comment by ywq0056** [comment]
I see. Thank you for your answer
