### ISSUE TITLE
script-opts to filter profile-list

### ISSUE THREAD

**Issue by butterw** [tsl0922/mpv-menu-plugin#29]
Proposed feature: it should be possible for the user to specify the filter to apply to the profile-list.
The #@profiles list contains default mpv profiles.
Some filtering is done:
```            
if not (profile.name == 'default' or profile.name:find('gui') or profile.name == 'encoding' or profile.name == 'libmpv')
...
```

gpu-hq is an alias for high-quality in mpv v0.37. 
sw-fast doesn't seem to have any use on windows.

dyn_menu.conf:
filter_profiles=default,encoding,libmpv,sw-fast,builtin-pseudo-gui,pseudo-gui,gpu-hq,sw-fast

**EDIT**: I don't know if a script-opts is required, maybe just add some filters ?

**Comment by tsl0922** [comment]
I don't think it's a big issue, if you think it matters, you may open a PR.

**Comment by hooke007** [comment]
Any profiles could be mod in input conf.

**Comment by butterw** [comment]
Runtime profile changes isn't really something I use. You have to be careful because applying a profile sets options on top of what is already existing, so if ex: you switch to gpu-hq then to fast, the result would potentially be quite different from directly applying fast. To avoid this, runtime profiles should include profile-restore=copy-equal.

The built-in profiles can be extended in mpv.conf (however changes to default don't seem to be applied on changes at runtime). I think only the most useful built-in profiles should be presented by default to avoid crowding-out user created profiles. Users may want to be able to configure the filter, in which case script-opts=dyn_menu-filter_profiles could be added.
