### ISSUE TITLE
Features: activate projects without closing the menu by combining shortcut keys

### ISSUE THREAD

**Issue by dyphire** [tsl0922/mpv-menu-plugin#3]
Optimize the use of repetitive operations.

The following is an example of the effects of related functions in the uosc menu:

https://github.com/tsl0922/mpv-plugin/assets/61936050/ccdbeb06-de24-403f-b889-c514cd04cf1f

**Comment by tsl0922** [comment]
Well, I don't think it's possible via the standand [menu api](https://learn.microsoft.com/en-us/windows/win32/menurc/using-menus) without hack.
