### ISSUE TITLE
creating an item without binding to a key

### ISSUE THREAD

**Issue by AdventurerRussia** [tsl0922/mpv-menu-plugin#33]
is it possible to create a menu item that will include the setting, but without a key?

**Comment by zhongfly** [comment]
readme already has a example:
```
_       ignore              #menu: Tracks #@tracks
```
no binding key, no command, only a menu item

**Comment by butterw** [comment]
with defaults (osc=no)
you can bind the key '_' and it will not show up in the menu.
put _ ignore at the end of input.conf to disable the keybinding. 

input.conf:
```
_ show-text "hello" #menu: hello

_ ignore 
```
