### ISSUE TITLE
Make states of menu public about it's shown or hidden.

### ISSUE THREAD

**Issue by natural-harmonia-gropius** [tsl0922/mpv-menu-plugin#34]
https://github.com/natural-harmonia-gropius/recent-menu/pull/20#issuecomment-1890907916
Third-party scripts don't know when the menu is shown or hidden.

Also https://github.com/tsl0922/mpv-menu-plugin/pull/19#issuecomment-1872539866

**Alt solution:**

https://github.com/natural-harmonia-gropius/recent-menu?tab=readme-ov-file#mpv-menu-plugin
The command part in input.conf of dynamic menu looks unused, what about call it when menu shown.

**Comment by tsl0922** [comment]
Why do you want to know if menu is shown or hidden?

**Comment by natural-harmonia-gropius** [comment]
如果我删除一个文件，调用uosc显示菜单会移除掉这一条

![image](https://github.com/tsl0922/mpv-menu-plugin/assets/50797982/6a2b407f-e480-440a-be04-c604c38d0a97)
![image](https://github.com/tsl0922/mpv-menu-plugin/assets/50797982/845ec972-9f91-4368-820e-584c2c9eeaae)

第二点，如果我开启多个mpv，a实例使菜单内容发生了改变，b实例的菜单仍然保持原样

**Comment by tsl0922** [comment]
那你继续发 `update` 消息更新不就可以了

**Comment by natural-harmonia-gropius** [comment]
**uosc:** 用户操作 打开菜单 -> myscript + json -> uosc - menu
**menu:** 用户操作 打开菜单 -> menu - show

缺少中间这一步，移除条目不会被触发，菜单事件没有，文件系统事件也没有。

另外即使我update，第二个例子的b实例也不会被a影响，没有任何通信手段。

**Comment by tsl0922** [comment]
其实是可以实现一样效果的，你可以在 input.conf 里 bind 你的脚本，然后你的脚本再 `script-message-to menu show` 来显示菜单。

**Comment by tsl0922** [comment]
只是这样确实不太优雅。。

**Comment by natural-harmonia-gropius** [comment]
也是

**Comment by natural-harmonia-gropius** [comment]
不对，如果多个脚本有这样的需求，input.conf只能调用其中一个的包装。

**Comment by tsl0922** [comment]
我觉得两者不太一样，uosc 的 open-menu 其实就是个 menu 样式的对话框，一次性的，所以可以设计成你说的那个流程。但是，menu 是个公共的菜单，不太可能设计成 uosc open-menu 那样的流程。

**Comment by tsl0922** [comment]
menu 插件在设计上就是只支持异步更新数据的，就你描述的场景而言，需要的是一个能在菜单显示前同步更新数据的机会，这个在现有的 mpv 机制下不太好做，毕竟标准的 message 都是异步的。如果真想做文件删除检查，那只能你自己写代码监听文件系统事件或者定时扫描了，发现变化就主动发 `update` 消息更新 menu。
