### ISSUE TITLE
[dyn_menu] update: ignored message with invalid keyword:

### ISSUE THREAD

**Issue by butterw** [tsl0922/mpv-menu-plugin#36]
I've implemented a #@window-scale dynamic menu using the new message interface. 
![](https://raw.githubusercontent.com/butterw/bShaders/7cad3427b74e14bcdaedfe73e6e6847bc65a949c/mpv/scr/mpv-menu-plugin_v2.1_btime.png)

I have the following issue: I get a warning message on each window-scale change if input conf doesn't contain my keyword:
```
[dyn_menu] update: ignored message with invalid keyword: window-scale
```

recentmenu.lua seems to have the same issue.

Is there a way to check keywords present in input.conf from my script ?

**Comment by butterw** [comment]
Reading the readme it seems I should possibly first send a get request then look for a possible error field in the reply. Then only send my update. This seems over-complicated (Either the keywords were in input.conf or they are not ?)  and isn't treated in the mpv-menu_test.lua example.

Couldn't this be simplified ? 
- keywords list placed in user-data
or keywords list sent as a parameter with menu-ready message.

**Comment by tsl0922** [comment]
The only way is to use the `get` message, or parsing `input.conf` yourself.

I don't think the message is an issue here, I can change it to debug if you still want to argue.

**Comment by butterw** [comment]
Works OK when the updates are done from menu-get-reply (menu-ready > get, if not reply.error > observe property > update).

The warning message is useful to alert to the issue with the update script, but only needs to be displayed to terminal once. Maybe it could also identify the script trying to update the menu with an invalid keyword.

**Comment by tsl0922** [comment]
> menu-get-reply: if not reply.error > observe property > update with keyword

you should check `data.keyword` too, because there may be multiple `get` messages for different keywords.

> but only needs to be displayed to terminal once

I don't think it's right (for debug), I will change it to debug level to avoid noisy.

**Comment by butterw** [comment]
Current is too noisy, but warning level does help ensure scripts are written properly.

Maybe limit to one invalid keyword warning then downgrade to debug.

**Comment by butterw** [comment]
checked #@window-scale menu:
https://github.com/butterw/bShaders/blob/master/mpv/settings/scripts/menu_window_scale.lua
