### ISSUE TITLE
dialog.lua

### ISSUE THREAD

**Issue by butterw** [tsl0922/mpv-menu-plugin#39]
Follow up from previous comments: https://github.com/tsl0922/mpv-menu-plugin/commit/f396ed100e81e53ee3e550bd8258a5bfbd9826da#commitcomment-137501902

> > OS Version? I'm on win10
> 
> Win10, Latest. default App mode: Light.

The extension are displayed when Explorer > View > x File Name Extensions. 

Unrelated, with the open files dialog, I've been getting warnings in the terminal window on right click on a file (caused by Google Drive apparently).
E0000 00:00:1705853244.858008   12128 ctxmenu.cc:212] UNKNOWN: From legacy status [type.googleapis.com/drive.ds.Status='UNKNOWN_STATUS']
=== Source Location Trace: ===
apps/drive/fs/ipc/shell_ipc_client.cc:588

**Comment by butterw** [comment]
_ script-message-to dialog open-clipboard  #menu: Open > Clipboard
broken for me with latest commit:

[dialog]
[dialog] stack traceback:
[dialog]        c:/mpc/mpv/portable_config/scripts/dialog.lua:69: in function 'handler'
[dialog]        mp.defaults:382: in function 'handler'
[dialog]        mp.defaults:512: in function 'call_event_handlers'
[dialog]        mp.defaults:554: in function 'dispatch_events'
[dialog]        mp.defaults:505: in function <mp.defaults:504>
[dialog]        [C]: at 0x7ff7c5b8fd00
[dialog]        [C]: at 0x7ff7c5b8e8f0
[dialog] Lua error: c:/mpc/mpv/portable_config/scripts/dialog.lua:44: attempt to compare number with string

**Comment by tsl0922** [comment]
> dialog.lua:44: attempt to compare number with string

Fixed.
