### ISSUE TITLE
Can I use the Clipboard like this picture?

### ISSUE THREAD

**Issue by candrapersada** [tsl0922/mpv-menu-plugin#41]
![image](https://github.com/tsl0922/mpv-menu-plugin/assets/36833664/f7d67810-e251-4052-96a6-ef762f2e5749)

**Comment by tsl0922** [comment]
No. The data in clipboard should be text (file path or url).

**Comment by butterw** [comment]
Win10: Shift + Right-click: Copy as path

**Comment by candrapersada** [comment]
```
[file] Cannot open file '"D:\driveid-156665-webrip-1080-terbit21-com-a-most-annoying-island-2019.mp4"': Invalid argument
Failed to open "D:\driveid-156665-webrip-1080-terbit21-com-a-most-annoying-island-2019.mp4".
Exiting... (Errors when loading file)
```

**Comment by butterw** [comment]
"On Windows 11, the Copy as path option appears in the context menu even if you don't hold the Shift key."
I think the format is: "filepath1\nfilepath2"  so " would need to be trimmed in local function clipboard_cb(clipboard)

**Comment by butterw** [comment]
- Copy now works
- Text path works with one file, 
- with multiple files: - works if the separator is LF not if CRLF (only plays the last file)
- Windows, Copy as path: chokes because of the quotes.

**Comment by tsl0922** [comment]
`\r` in line breaks is supported now.
