### ISSUE TITLE
Default name in file dialog contains extra quotes

### ISSUE THREAD

**Issue by Youxikong** [tsl0922/mpv-menu-plugin#42]
If set `user-data/menu/dialog/default-name` as a string, then send script message to open file diaglog, the default name contain a pair of quotes.

![image](https://github.com/tsl0922/mpv-menu-plugin/assets/26603498/af729be7-c116-4d22-8b1b-fa538f9b9c1e)

**Comment by tsl0922** [comment]
Upstream issue: https://github.com/mpv-player/mpv/issues/13344

**Comment by tsl0922** [comment]
I've pushed a fix for it, `mpv_get_property(mpv, '...', MPV_FORMAT_NODE)` works fine.
