### ISSUE TITLE
[dialog.lua] Add video track and playlist check before send `dialog/save` message to menu.dll

### ISSUE THREAD

**Issue by Youxikong** [tsl0922/mpv-menu-plugin#43]
Thanks to your contribution, it maybe the best mpv sricpt on Windows.
I found a problem of screenshot/playlist saving logic in `dialog.lua`. If there is no video track or playlist, it will also send message and prompt a file dialog but do nothing but a osd message. So I suggest to add video track and playlist check before.
For example, add:
```
if not mp.get_property_number('vid') then
    mp.osd_message('No video track')
    return
end
```
between line 193 and 194, and add:
```
if mp.get_property_number('playlist-count', 0) == 0 then
    mp.osd_message('Playlist is empty')
    return
end
```
between line 201 and 202.

**Comment by tsl0922** [comment]
Your may send a pull requests

**Comment by tsl0922** [comment]
I'm still considering a new keyword to disable menu item based on property (like  `#@prop:check`), with it the check here will no longer be needed.

**Comment by Youxikong** [comment]
This feature cannot prevent command triggered by input or other scripts.
