### ISSUE TITLE
mpv auto exit after  `open-clipboard` with an unknown file or directory

### ISSUE THREAD

**Issue by verygoodlee** [tsl0922/mpv-menu-plugin#48]
`Ctrl+v      script-message-to dialog open-clipboard #menu: Open > Clipboard`

Unknown file
![image](https://github.com/tsl0922/mpv-menu-plugin/assets/45035465/357ae7af-5d69-4a2e-a26f-28f76a02c46d)

This is also triggered if the filename uses quotation marks, such as `"E:\test.mp4"`, 
the quotation marks must be removed to work properly

**Comment by tsl0922** [comment]
It has nothing to do with this plugin. This is mpv's default behaviour, exit after finishing playback. If you don't want it, start mpv with `--idle=yes`.

**Comment by verygoodlee** [comment]
If the clipboard content is not a protocol, check whether the file exists.
verygoodlee/mpv-menu-plugin@7ecacde

It should be more efficient if implemented in C

**Comment by tsl0922** [comment]
You can check it in `clipboard_cb`.

**Comment by verygoodlee** [comment]
verygoodlee/mpv-menu-plugin@7fb5349 It's much better
