### ISSUE TITLE
Not working.

### ISSUE THREAD

**Issue by wrhou** [tsl0922/mpv-menu-plugin#49]
I've added `MBTN_RIGHT script-message-to menu show` to input.conf, but nothing happens when I open a video and right click on the viewport (doesn't pause/play)

These files are in place and unmodified as per instructions:
```
%appdata%\mpv\scripts\dyn_menu.lua
%appdata%\mpv\scripts\menu.dll
%appdata%\mpv\scripts\dialog.lua
```

mpv-menu-plugin Release 2.3.0 

mpv v0.37.0-229-gc6ccabe5 Copyright © 2000-2024 mpv/MPlayer/mplayer2 projects
 built on Jan 28 2024 00:11:42

Many thanks

**Comment by tsl0922** [comment]
Have you defined some menu items in `input.conf`? you may want to get start from the example conf:

https://gist.github.com/tsl0922/8989aa32994b0448a2652ee260348a35

**Comment by wrhou** [comment]
Oh...... that's a blunder on my part.
Thank you!

**Comment by tsl0922** [comment]
> Will there be a feature is the default pre-configured menu if none is defined in your `input.conf` like in mpv.net?

No.

This plugin is for vanilla mpv, I don't want to override user's `input.conf`, mpv.net is another player, so it can embed a custom `input.conf`.
