### ISSUE TITLE
The menu stops working when vo changed

### ISSUE THREAD

**Issue by 0jk** [tsl0922/mpv-menu-plugin#52]
The menu does not appear if changing vo via console or profiles. The same for gpu-api. Might not work work other cases as well.

Workaround is staring mpv with required options/profile.

Version: mpv v0.37.0-271-gf5c4f0b0

**Comment by tsl0922** [comment]
mpv does not send a `window-id` change event on vo change.

I have filed an issue on upstream: https://github.com/mpv-player/mpv/issues/13495

**Comment by tsl0922** [comment]
It has been fixed by mpv.
