### ISSUE TITLE
大佬请改下码率显示长度

### ISSUE THREAD

**Issue by redomCL** [tsl0922/mpv-menu-plugin#55]
大佬请改下码率显示长度，蓝光原盘有一些音频码率上千，3位数长度会导致显示不正常
if track['demux-bitrate'] then h(string.format('%.4g kbps', track['demux-bitrate'] / 1000)) end
![2](https://github.com/tsl0922/mpv-menu-plugin/assets/22269254/89080849-f642-4420-83d8-3de413e8b9f9)
![3](https://github.com/tsl0922/mpv-menu-plugin/assets/22269254/f52dc6fd-cbd6-406d-b18e-5d19b358c3a0)

**Comment by tsl0922** [comment]
都加到 5 位了。
