### ISSUE TITLE
The menu is not black

### ISSUE THREAD

**Issue by watcherhd** [tsl0922/mpv-menu-plugin#56]
The menu is white - how to change it?
![5SBvofVpAA](https://github.com/tsl0922/mpv-menu-plugin/assets/6558205/2ba037ef-c29b-44cd-a7f3-682cb15789f9)

**Comment by tsl0922** [comment]
https://github.com/tsl0922/mpv-menu-plugin/wiki/FAQ

**Comment by watcherhd** [comment]
thx - my bsd - didn't close and reopen player after the dark mode change, sorry

**Comment by candrapersada** [comment]
how to Turn on Dark mode in Windows 7?
https://github.com/mpv-player/mpv/issues/13093#
