### ISSUE TITLE
 B站播放列表不显示标题

### ISSUE THREAD

**Issue by Trudeau566** [tsl0922/mpv-menu-plugin#68]
只显示网址，怎么像左边一样显示标题？
![PixPin_2024-06-18_06-19-07](https://github.com/tsl0922/mpv-menu-plugin/assets/118544592/26896f34-cfb1-4355-bfc6-8e4b7841b4a1)

**Comment by hooke007** [comment]
你左边的脚本是不是用了ytdlp遍历预处理了一遍

**Comment by hooke007** [comment]
你左边的脚本是不是用了ytdlp遍历预处理了一遍

**Comment by Trudeau566** [comment]
> 你左边的脚本是不是用了ytdlp遍历预处理了一遍

左边的脚本开启了这项就会显示标题resolve_url_titles=yes
右边菜单了的能不能也显示标题？

**Comment by hooke007** [comment]
> resolve_url_titles=yes

https://github.com/jonniek/mpv-playlistmanager?tab=readme-ov-file#title-resolving
所以是外部程序实现的

**Comment by dyphire** [comment]
playlistmanager 的解析 url 标题的实现比较 hack，不适合移植到其他脚本。但可以利用 mpv 的 `user-data` 属性传递解析好的标题数据让感兴趣的其他脚本调用它

playlistmanager 上的 PR ：https://github.com/jonniek/mpv-playlistmanager/pull/144
uosc 上的使用示例：https://github.com/dyphire/uosc/commit/3c1fc94565ee0ccb44198146bb4d5a9b94c1e1d9

但是 mpv-menu-plugin 的脚本无法很好地利用这个方式，因为它的播放列表菜单只有`playlist`属性变化时才会刷新，无法实现监控对应的`user-data` 属性来进行刷新菜单。除非更改为 uosc 的菜单刷新方式否则无法很好的解决这一点

**Comment by tsl0922** [comment]
暂不考虑在这个插件实现此功能。
