### ISSUE TITLE
字幕轨道列表可以显示完整的外挂字幕文件名吗

### ISSUE THREAD

**Issue by CNhjx** [tsl0922/mpv-menu-plugin#69]
input.conf：Ctrl+s cycle sub #menu: 字幕 > ※主字幕※ #@tracks/sub
![image](https://github.com/tsl0922/mpv-menu-plugin/assets/57735696/31f5ea8f-8aa6-4809-9372-245bedc830ac)
菜单中字幕轨道只显示 “Sub+编号+文件类型”。
可以显示完整的文件名吗，就像切换字幕时osd显示的内容
![image](https://github.com/tsl0922/mpv-menu-plugin/assets/57735696/2e7595fa-1efd-454f-94fa-423e476d3edc)

**Comment by tsl0922** [comment]
可以做到，但是没必要，文件名太长了，显示在菜单上不好看。

**Comment by CNhjx** [comment]
可以截断省略，如果有多个外挂字幕，在这个列表就不好区分选择

**Comment by CNhjx** [comment]
可以截断省略吗，如果有多个外挂字幕，在这个列表不好区分选择

**Comment by tsl0922** [comment]
菜单都在 lua 代码里生成的，有兴趣可以自己改。

**Comment by CNhjx** [comment]
dyn_menu和dialog两个lua分别负责的什么部分呢

**Comment by tsl0922** [comment]
你直接修改 dyn_menu.lua 里的 `build_track_title` 方法就可以了。

**Comment by CNhjx** [comment]
好的，非常感谢

**Comment by CNhjx** [comment]
> 你直接修改 dyn_menu.lua 里的 `build_track_title` 方法就可以了。

发现一个小问题，貌似菜单获取文件名filename会省略掉&符号，文件名中出现“~&&~”只会在显示一个“&”，%@_这些符号不会，在dyn_menu.lua和dialog.lua好像没有找到相关的设置
![image](https://github.com/tsl0922/mpv-menu-plugin/assets/57735696/9f8b8112-f06e-40a5-a826-c9f88e066f5a)

**Comment by CNhjx** [comment]
> 你直接修改 dyn_menu.lua 里的 `build_track_title` 方法就可以了。

发现一个小问题，貌似菜单获取title会省略掉&符号，文件名中出现“&&”只会在显示一个“&”，%@_这些符号不会，在dyn_menu.lua和dialog.lua好像没有找到相关的设置
![image](https://github.com/tsl0922/mpv-menu-plugin/assets/57735696/d7691844-240a-4599-b519-9be6dd7191b6)

**Comment by tsl0922** [comment]
dyn_menu 更新到最新版本了吗？这个默认就有转义的啊

**Comment by CNhjx** [comment]
是最新的2.4.1

**Comment by CNhjx** [comment]
> dyn_menu 更新到最新版本了吗？这个默认就有转义的啊
使用dev中的menu正常了

**Comment by CNhjx** [comment]
请问轨道右侧显示缩写的语言栏是最多就支持三个字符吗
我加了些if想显示unknow或者zh&en这样的

**Comment by CNhjx** [comment]
dyn_menu使用dev版本
我在items部分加了下列代码，为了实现显示外挂轨道列表右侧语言栏缩写
            if track.external then
                if track.lang ~= nir then 
                    language = track.lang:upper()
                else
                    local dot = string.find(build_track_title(track, prefix, filename), '%.')
                        if dot then
                            language = string.gsub(build_track_title(track, prefix, filename),'(%..-)$',''):upper()
                        else
                            language = 'UNKNOWN'
                        end
                end
            else
                language=(track.lang and track.lang ~= '') and track.lang:upper() or 'UNKNOWN'
            end

            items[#items + 1] = {
                title = build_track_title(track, prefix, filename),
                shortcut = language,
                cmd = string.format('set %s %d', prop, track.id),
                state = state,
            }
发现右侧显示的时候同样会出现单个'&'消失，和后面小写字母形成字母+下划线，多个&会省略一个。
非常困惑
![image](https://github.com/tsl0922/mpv-menu-plugin/assets/57735696/de670e09-707d-483e-90dd-404c2a13fd12)

**Comment by CNhjx** [comment]
dyn_menu使用dev版本
我在items部分加了下列代码，为了实现显示外挂轨道列表右侧语言栏缩写
if track.external then
if track.lang ~= nir then
language = track.lang:upper()
else
local dot = string.find(build_track_title(track, prefix, filename), '%.')
if dot then
language = string.gsub(build_track_title(track, prefix, filename),'(%..-)$',''):upper()
else
language = 'UNKNOWN'
end
end
else
language=(track.lang and track.lang ~= '') and track.lang:upper() or 'UNKNOWN'
end

        items[#items + 1] = {
            title = build_track_title(track, prefix, filename),
            shortcut = language,
            cmd = string.format('set %s %d', prop, track.id),
            state = state,
        }
发现右侧显示的时候同样会出现单个'&'消失，和后面字母形成字母+下划线，多个&会省略一个。
![image](https://github.com/tsl0922/mpv-menu-plugin/assets/57735696/e880b1b8-457e-4c53-9203-1235cfbb6bf2)
![image](https://github.com/tsl0922/mpv-menu-plugin/assets/57735696/080b2303-f7e6-4a56-889d-3484750b8624)

非常困惑

**Comment by CNhjx** [comment]
好的，解决了
