### ISSUE TITLE
播放列表文件标题缩略有点问题

### ISSUE THREAD

**Issue by verygoodlee** [tsl0922/mpv-menu-plugin#70]
以默认`max_title_length=80`为例

`mpv any.mp4 --force-media-title="测试1测试2测试3测试4测试5测试6测试7测试8测 试9测试10测试11测试12"`
展示的是完整标题，但是后面有省略号，完整标题的话省略号是不应该出现的
![image](https://github.com/tsl0922/mpv-menu-plugin/assets/45035465/4bc5a26a-e2f7-4ff4-8644-563a24455157)

问题应该出在这个判断，`str:len()`获取的不是字符数而是字节数，应该要另外写个函数获取utf8字符数
https://github.com/tsl0922/mpv-menu-plugin/blob/c237760f0aa77ddde81af486638822caee32e763/src/lua/dyn_menu.lua#L177-L179

或者不在截取前判断，先截取，截取后再判断，截取后的字节数比原始字节数更小则说明标题不完整，添加省略号
```lua
    local original_len = str:len()
    str = o.max_title_length > 0 and utf8_sub(str, 1, o.max_title_length) or str
    if str:len() < original_len then str = str .. '...' end
    return str
```

**Comment by tsl0922** [comment]
已修复，试下最新的代码。

**Comment by dyphire** [comment]
实际上新的实现还是存在问题，CJK 字符的宽度和罗马字符的宽度并不相同，基于同样的长度缩写是不合理的

**Comment by verygoodlee** [comment]
至少在lua脚本层面无法保证宽度一致，UI字体一般都非等宽（Windows是Microsoft YaHei UI），即使同为英文字符差距也很大，`i` `l` 差不多只有 `a` `b`的1/3，跟大写`W`比差不多1/6，大写`W`几乎与中文差不多。

如果win32菜单有方法限制宽度，在C插件内才能解决。

**Comment by dyphire** [comment]
> 至少在 lua 脚本层面无法保证宽度一致，UI 字体一般都非等宽（Windows 是 Microsoft YaHei UI），即使同为英文字符差距也很大，`i` `l` 差不多只有 `a` `b` 的 1/3，跟大写 `W` 比差不多 1/6，大写 `W` 几乎与中文差不多。
> 
> 如果 win32 菜单有方法限制宽度，在 C 插件内才能解决。

你把事情想复杂了，这里并不需要严格的字符宽度测量。它只用于菜单标题的自定义缩写，而不是 UI 元素的溢出截断检测；后者是 console.lua 和 uosc 中需要做的，除非菜单脚本改为自动测量标题宽度并自动决定缩写的形式否则不需要精准的宽度

以等宽字体的宽度比为基准在一定的字符数量范围内和一般非等宽字体的显示误差只在几个字符的差异内，这个误差是可以接受的，已经比现有的基于相同字符数量的方法好多了。这个功能不值得进一步复杂化

该方法在某些特殊字体下误差可能会更大，但这个菜单会应用的只有系统字体，不受影响
