### ISSUE TITLE
misidentification of submenu

### ISSUE THREAD

**Issue by hooke007** [tsl0922/mpv-menu-plugin#9]
`#      #! test`

![Snipaste_2023-12-16_00-34-19](https://github.com/tsl0922/mpv-plugin/assets/41094733/20f8d07d-a80c-44ae-aa0c-622458207d6a)

**Comment by tsl0922** [comment]
Can not reproduce with the latest Actions build.

**Comment by hooke007** [comment]
![Snipaste_2023-12-16_09-59-41](https://github.com/tsl0922/mpv-plugin/assets/41094733/8283897d-785d-479c-ae21-2379eed56762)
![Snipaste_2023-12-16_09-59-59](https://github.com/tsl0922/mpv-plugin/assets/41094733/065ca27b-93fa-4f60-8c8e-2514d1b75c27)
Tested on Win 11 23H2 + latest mpv + latest Actions build of menu.

**Comment by tsl0922** [comment]
```
#define WHITESPACE " \f\n\r\t\v"
```

Characters that not one of the char in `WHITESPACE` will not be stripped.

**Comment by tsl0922** [comment]
Have you checked other system app's menu on your machine? The menu is created via native win32 API, I didn't do anything special to the text padding in menu item, it should all be system behaviour.

**Comment by hooke007** [comment]
It can be reproduced in the sandbox.

![PixPin_2024-01-08_20-06-11](https://github.com/tsl0922/mpv-menu-plugin/assets/41094733/a0f43b93-db95-4576-a404-c2b94494b846)


> Have you checked other system app's menu on your machine? 

What does it mean? Never noticed sth special.

**Comment by tsl0922** [comment]
You may take a look at: https://github.com/hooke007/MPV_lazy/discussions/401#discussioncomment-8038876
The left side of space is similar to it, may be reserved space for menu icon or padding by system api.

**TDLR:** It's system behaviour, I have no plan to change it.
